## video 1.2.1

In [ ]:
import pandas as pd

#### Load the Titanic data-set, clean it up

In [2]:
df = pd.read_csv("titanic.csv")
df.head()       ## you can also see .tail

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.info()              # Information : dtypes + non-null counts per column

In [5]:
print(df.Age)

In [6]:
df.isna().sum()          # missing values per column

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
df.duplicated().sum()    # how many duplicate rows?

np.int64(0)

In [8]:
df["Embarked"].unique()  # How many unique values of 'Embarked'?

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

Highlight why median is a safer default than mean for Age (a few very old or very young passengers can skew the mean),

In [9]:
df["Age"] = df["Age"].fillna(df["Age"].median())   # fill missing Age with the median

In [10]:
df.isna().sum()    # check missing values again

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
df["Embarked"].isna()   # Which has no 'Embarked' value?

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Embarked, Length: 891, dtype: bool

In [12]:
df[df["Embarked"].isna()]     # Show the full row

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [19]:
df.iloc[829]       # Show row 829   use "iloc" for for integer-position-based selection

PassengerId                                           830
Survived                                                1
Pclass                                                  1
Name            Stone, Mrs. George Nelson (Martha Evelyn)
Sex                                                female
Age                                                  62.0
SibSp                                                   0
Parch                                                   0
Ticket                                             113572
Fare                                                 80.0
Cabin                                                 B28
Embarked                                                S
Pclass_label                                        First
Name: 829, dtype: object

In [14]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])  # fill missing Embarked with the most common port

In [18]:
df.loc[829,'Embarked']   #Check row 829 again, use "loc" for label-based selection

'S'

In [16]:
# create a readable category instead of raw class numbers

df["Pclass_label"] = df["Pclass"].map({1: "First", 2: "Second", 3: "Third"})
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass_label
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Third
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,First
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Third
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,First
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Third

## Video 1.2.2

In [ ]:
df.describe()     # Show some overall statistics : mean, std, quartiles for numeric columns

In [ ]:
df.columns

#### How many survived per gender

In [ ]:
df.groupby("Sex")["Survived"].mean()

#### How many survived per Class

In [ ]:
df.groupby("Pclass_label")["Survived"].mean().sort_values(ascending=False)

#### Surevival rate per gender and Class

In [ ]:
df.groupby(["Pclass_label", "Sex"]).agg(
    survival_rate=("Survived", "mean"),
    avg_fare=("Fare", "mean"),
    n_passengers=("PassengerId", "count")
)

Talking point: Ask students to interpret the sign and strength of each correlation before revealing the answer:

Fare correlates positively with survival (wealthier passengers had better cabin access to lifeboats).

Pclass correlates negatively (class 1 = 1, class 3 = 3, so a negative correlation with survival means higher class number → lower survival, i.e., third class fared worst).

In [ ]:
numeric_cols = ["Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]

df[numeric_cols].corr()["Survived"].sort_values(ascending=False)

In [ ]:
import pandas as pd
df = pd.read_csv("sales.csv")

1. look at basic stats for `quantity` — does anything stand out?

2. Threshold =  the 99th percentile of `quantity` using   df["quantity"].quantile(0.99)

3. All rows with quanteties above the Threshold are "outliers"

4. Calculate the average sales revenue for the outliers only, and for all the rows

5. which category had the overall biggest revenue

## Video 1.2.3

## Solutions

1. look at basic stats for `quantity` — does anything stand out?

In [ ]:
df["quantity"].describe()

2. Threshold =  the 99th percentile of `quantity` using   df["quantity"].quantile(0.99)

In [ ]:
threshold = df["quantity"].quantile(0.99)
threshold

In [ ]:
df["quantity"].hist(
    bins=10,
    edgecolor="black"
)

plt.title("Distribution of Quantity")
plt.xlabel("Quantity")
plt.ylabel("Number of Rows")
#plt.ylim(0, 50)
plt.show()

3. All rows with quanteties above the Threshold are "outliers"

In [ ]:
outliers = df[df["quantity"] > threshold]

4. Calculate the average sales revenue for the outliers only, and for all the rows

In [ ]:
print("Outlier avg revenue:", outliers["revenue"].mean().round(2))
print("Overall avg revenue:", df["revenue"].mean().round(2))

5. which category had the overall biggest revenue

In [ ]:
df.groupby("category")["revenue"].sum().sort_values(ascending=False)